name: Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

permissions:
  contents: write
  pages: write # to deploy to Pages
  id-token: write # to verify the deployment originates from an appropriate source

jobs:
  build_docs:
    name: Build docs
    uses: ./.github/workflows/build_docs.yml

  deploy:
    needs: build_docs

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
